// Mock data for the AI Career Agent Platform
import type { Job, MarketData, EmailNotification, CalendarEvent, User } from '../types';

export const mockUser: User = {
  id: 'user-1',
  name: 'Alex Johnson',
  email: 'alex.johnson@email.com',
  careerStage: 'graduate',
  graduationDate: '2025-05-15',
  targetRole: 'Software Engineer',
  skills: ['JavaScript', 'React', 'Python', 'AWS', 'Node.js'],
  preferences: {
    jobAlerts: true,
    emailNotifications: true,
    locations: ['San Francisco', 'Remote', 'New York'],
    industries: ['Technology', 'Finance', 'Healthcare'],
    salaryRange: { min: 80000, max: 130000 },
    remotePreference: 'hybrid',
  },
};

export const mockJobs: Job[] = [
  {
    id: 'job-1',
    title: 'Senior Software Engineer',
    company: 'TechCorp Inc.',
    location: 'San Francisco, CA',
    type: 'full-time',
    remote: true,
    salary: { min: 120000, max: 180000 },
    description: 'Join our innovative team building next-generation cloud solutions.',
    requirements: ['5+ years React', 'AWS experience', 'TypeScript', 'CI/CD'],
    benefits: ['Health insurance', '401k matching', 'Remote work', 'Stock options'],
    postedDate: '2025-10-18',
    source: 'LinkedIn',
    aiScore: 94,
    matchAnalysis: {
      skillsMatch: 92,
      experienceMatch: 88,
      locationMatch: 100,
      salaryMatch: 95,
      overallFit: 'Excellent match based on your React and AWS expertise. The remote option aligns with your preferences.',
    },
    applicationStatus: 'not-applied',
  },
  {
    id: 'job-2',
    title: 'Full Stack Developer',
    company: 'InnovateLabs',
    location: 'Remote',
    type: 'full-time',
    remote: true,
    salary: { min: 100000, max: 140000 },
    description: 'Build scalable web applications using modern JavaScript frameworks.',
    requirements: ['Node.js', 'React', 'MongoDB', 'REST APIs'],
    benefits: ['Flexible hours', 'Professional development', 'Health benefits'],
    postedDate: '2025-10-19',
    source: 'Indeed',
    aiScore: 89,
    matchAnalysis: {
      skillsMatch: 95,
      experienceMatch: 85,
      locationMatch: 100,
      salaryMatch: 80,
      overallFit: 'Strong fit with your full-stack skills. Great opportunity for remote work.',
    },
    applicationStatus: 'applied',
  },
  {
    id: 'job-3',
    title: 'Frontend Engineer',
    company: 'Digital Dynamics',
    location: 'New York, NY',
    type: 'full-time',
    remote: false,
    salary: { min: 110000, max: 150000 },
    description: 'Create beautiful, responsive user interfaces for enterprise applications.',
    requirements: ['React', 'TypeScript', 'CSS/SASS', 'Testing'],
    benefits: ['Competitive salary', 'Transit benefits', 'Learning budget'],
    postedDate: '2025-10-20',
    source: 'Glassdoor',
    aiScore: 85,
    matchAnalysis: {
      skillsMatch: 90,
      experienceMatch: 82,
      locationMatch: 85,
      salaryMatch: 88,
      overallFit: 'Good match for your frontend expertise. Consider the commute vs benefits.',
    },
    applicationStatus: 'not-applied',
  },
  {
    id: 'job-4',
    title: 'Cloud Solutions Architect',
    company: 'CloudNative Systems',
    location: 'Austin, TX',
    type: 'full-time',
    remote: true,
    salary: { min: 130000, max: 190000 },
    description: 'Design and implement cloud infrastructure solutions for enterprise clients.',
    requirements: ['AWS certification', 'Terraform', 'Kubernetes', '7+ years experience'],
    benefits: ['Top-tier compensation', 'Unlimited PTO', 'Remote-first culture'],
    postedDate: '2025-10-17',
    source: 'LinkedIn',
    aiScore: 78,
    matchAnalysis: {
      skillsMatch: 75,
      experienceMatch: 70,
      locationMatch: 100,
      salaryMatch: 92,
      overallFit: 'Good opportunity to grow your AWS skills. May need additional certifications.',
    },
    applicationStatus: 'not-applied',
  },
  {
    id: 'job-5',
    title: 'Software Development Engineer',
    company: 'Amazon Web Services',
    location: 'Seattle, WA',
    type: 'full-time',
    remote: false,
    salary: { min: 140000, max: 200000 },
    description: 'Build and scale AWS services used by millions of customers worldwide.',
    requirements: ['Computer Science degree', 'System design', 'Java/Python', 'Distributed systems'],
    benefits: ['RSUs', 'Relocation assistance', 'Career growth', 'World-class team'],
    postedDate: '2025-10-21',
    source: 'Custom',
    aiScore: 92,
    matchAnalysis: {
      skillsMatch: 88,
      experienceMatch: 86,
      locationMatch: 75,
      salaryMatch: 98,
      overallFit: 'Exceptional opportunity at a top tech company. High compensation and career growth potential.',
    },
    applicationStatus: 'interview',
  },
  {
    id: 'job-6',
    title: 'Junior Software Engineer',
    company: 'StartupX',
    location: 'San Francisco, CA',
    type: 'full-time',
    remote: true,
    salary: { min: 85000, max: 115000 },
    description: 'Join a fast-growing startup and make an immediate impact.',
    requirements: ['React', 'JavaScript', '1-2 years experience', 'Startup mentality'],
    benefits: ['Equity', 'Flexible schedule', 'Learning opportunities'],
    postedDate: '2025-10-20',
    source: 'Indeed',
    aiScore: 81,
    matchAnalysis: {
      skillsMatch: 85,
      experienceMatch: 90,
      locationMatch: 100,
      salaryMatch: 72,
      overallFit: 'Great entry-level opportunity with equity upside. Perfect for recent graduates.',
    },
    applicationStatus: 'not-applied',
  },
];

export const mockMarketData: MarketData = {
  salaryTrends: [
    { role: 'Software Engineer', avgSalary: 120000, trend: 8.5, location: 'San Francisco' },
    { role: 'Frontend Developer', avgSalary: 105000, trend: 6.2, location: 'New York' },
    { role: 'Full Stack Engineer', avgSalary: 115000, trend: 9.1, location: 'Remote' },
    { role: 'Cloud Architect', avgSalary: 150000, trend: 12.3, location: 'Seattle' },
    { role: 'DevOps Engineer', avgSalary: 125000, trend: 10.7, location: 'Austin' },
  ],
  skillDemand: [
    { skill: 'React', demand: 95, growth: 15.2 },
    { skill: 'AWS', demand: 88, growth: 22.5 },
    { skill: 'Python', demand: 92, growth: 18.3 },
    { skill: 'Kubernetes', demand: 78, growth: 28.7 },
    { skill: 'TypeScript', demand: 85, growth: 25.1 },
    { skill: 'Node.js', demand: 82, growth: 12.8 },
    { skill: 'Docker', demand: 80, growth: 16.4 },
    { skill: 'GraphQL', demand: 65, growth: 31.2 },
  ],
  industryTrends: [
    { industry: 'Technology', jobCount: 15420, avgSalary: 125000, growth: 14.5 },
    { industry: 'Finance', jobCount: 8750, avgSalary: 135000, growth: 8.2 },
    { industry: 'Healthcare', jobCount: 6230, avgSalary: 110000, growth: 12.8 },
    { industry: 'E-commerce', jobCount: 9870, avgSalary: 118000, growth: 18.6 },
    { industry: 'Consulting', jobCount: 5430, avgSalary: 128000, growth: 6.9 },
  ],
};

export const mockEmails: EmailNotification[] = [
  {
    id: 'email-1',
    type: 'interview',
    subject: 'Interview Invitation - Software Development Engineer Position',
    sender: 'recruiting@amazon.com',
    receivedDate: '2025-10-21T09:30:00',
    content: 'Congratulations! We would like to invite you for a technical interview...',
    actionRequired: true,
    calendarEvent: {
      id: 'cal-1',
      title: 'AWS Technical Interview',
      date: '2025-10-25',
      time: '14:00',
      location: 'Virtual (Zoom)',
      meetingLink: 'https://zoom.us/j/example123',
      company: 'Amazon Web Services',
      type: 'interview',
    },
  },
  {
    id: 'email-2',
    type: 'application-update',
    subject: 'Application Update - Full Stack Developer',
    sender: 'hr@innovatelabs.com',
    receivedDate: '2025-10-20T15:45:00',
    content: 'Thank you for your application. We are currently reviewing...',
    actionRequired: false,
  },
  {
    id: 'email-3',
    type: 'interview',
    subject: 'Schedule Your Interview - TechCorp Inc.',
    sender: 'talent@techcorp.com',
    receivedDate: '2025-10-19T11:20:00',
    content: 'We are impressed with your background and would like to schedule...',
    actionRequired: true,
    calendarEvent: {
      id: 'cal-2',
      title: 'TechCorp Hiring Manager Interview',
      date: '2025-10-24',
      time: '10:00',
      location: 'TechCorp Office, SF',
      company: 'TechCorp Inc.',
      type: 'interview',
    },
  },
];

export const mockCalendarEvents: CalendarEvent[] = [
  ...mockEmails.filter(e => e.calendarEvent).map(e => e.calendarEvent!),
  {
    id: 'cal-3',
    title: 'Career Fair - Tech Companies',
    date: '2025-10-28',
    time: '13:00',
    location: 'Convention Center',
    company: 'Multiple',
    type: 'networking',
  },
  {
    id: 'cal-4',
    title: 'Application Deadline - StartupX',
    date: '2025-10-23',
    time: '23:59',
    location: 'Online',
    company: 'StartupX',
    type: 'deadline',
  },
];
